import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className="container mx-auto">
        <main className="flex flex-col justify-between min-h-screen ">
          <header >hello</header>
        {children}
        </main>
      </body>
    </html>
  );
}
